# -*- coding: utf-8 -*-
"""RecursionLK

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PiFaY72sP9u-syY97drMjudNNeBkxJGZ
"""

n = int(input("Enter an integer: "))
def sum(n):
    if n == 1:
        return 1
    else:
        return n + sum(n - 1)
print(f"The sum of numbers from 1 to 5 is: {sum(n)}")

string = input("Enter a string: ")
def reverse(string):
  if len(string) == 1:
    return string
  else:
    return reverse(string[1:]) + string[0]
print(f"The reverse of {string} is: {reverse(string)}")

s = input("Enter a string: ")
def palindrome(s):
  if len(s) == 1:
    return s
  else:
    return palindrome(s[1:])+s[0]
if s == palindrome(s):
  print(f"{s} is a palindrome!!")
else:
  print(f"{s} is not a palindrome...")

n = int(input("Enter an integer: "))
def factorial(n):
  if n == 0:
    return 1
  else:
    return n * factorial(n-1)
print(f"{n}! = {factorial(n)}")

# The formula of the Fibonacci series is Fib(n) = Fib(n-1) + Fib(n-2) so the last line is wrong and we need to replace the last n by fibonacci(n-2).

#Q1 is B

#Q2 is B

#Q3 is D

#Q4 is C

#Q5 is C